// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class T3Test {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void t3() {
    driver.Navigate().GoToUrl("http://softuni-qa-loadbalancer-2137572849.eu-north-1.elb.amazonaws.com:83/");
    driver.Manage().Window.Size = new System.Drawing.Size(1536, 816);
    driver.FindElement(By.CssSelector(".btn-outline-info")).Click();
    driver.FindElement(By.Id("typeEmailX-2")).Click();
    driver.FindElement(By.Id("typeEmailX-2")).SendKeys("iv1234@test.com");
    driver.FindElement(By.Id("typePasswordX-2")).Click();
    driver.FindElement(By.Id("typePasswordX-2")).SendKeys("123456");
    driver.FindElement(By.CssSelector(".ripple-surface")).Click();
    driver.FindElement(By.LinkText("My Ideas")).Click();
    driver.FindElement(By.CssSelector(".ripple-surface")).Click();
    driver.FindElement(By.CssSelector(".mb-0")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".mb-0")).Text, Is.EqualTo("iiii"));
    driver.FindElement(By.CssSelector(".me-3")).Click();
    driver.Close();
  }
}
